spring:
  application:
    name: file-api
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
      max-file-size: 10MB

file:
  upload:
    directory: "./uploads"