name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        id: check-code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: set-jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Cache Maven packages
        id: cache-mvn-packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run Tests
        id: run-test
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-api
          path: target/*.jar
          compression-level: 7